---
services:
  sql1:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Passw0rd"
    ports:
      - "1433:1433"
    container_name: sql1
    hostname: sql1
    restart: always
